services:
  frontend:
    build: ./frontend
    container_name: front
    ports:
      - '3050:3050'
    stdin_open: true
    tty: true
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mern-networks
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:5050
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=3050"
      - "prometheus.path=/metrics"

  backend:
    build: ./backend
    container_name: back
    ports:
      - '5050:5050'
    restart: always
    networks:
      - mern-networks
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5050
      - MONGO_URI=mongodb://mongo:27017/your_database
      - ENABLE_METRICS=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5050/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      mongo:
        condition: service_healthy
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=5050"
      - "prometheus.path=/metrics"

  mongo:
    image: mongo:4.4
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-networks
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo-exporter:
    image: percona/mongodb_exporter:latest
    container_name: mongo-exporter
    restart: always
    ports:
      - "9216:9216"
    command:
      - '--mongodb.uri=mongodb://mongo:27017'
      - '--compatible-mode'
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mern-networks
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=9216"
      - "prometheus.path=/metrics"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - mern-networks
    depends_on:
      - backend
      - frontend
      - mongo-exporter
      - node-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - mern-networks
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - mern-networks
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=9100"

volumes:
  mongo-data:
  prometheus-data:
  grafana-data:

networks:
  mern-networks:
    driver: bridge