global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance_name: "Prometheus Server"

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['vente-node-exporter:9100']
        labels:
          instance_name: "System Metrics"

  - job_name: 'backend'
    static_configs:
      - targets: ['vente-backend:5050']
        labels:
          instance_name: "Backend Application"
    metrics_path: /metrics

  - job_name: 'frontend'
    static_configs:
      - targets: ['vente-frontend:3000']
        labels:
          instance_name: "Frontend Application"
    metrics_path: /metrics

  - job_name: 'mongo'
    static_configs:
      - targets: ['vente-mongo-exporter:9216']
        labels:
          instance_name: "MongoDB Metrics"